# Not to be confused with the Python version, specified in Dockerfile ;)
version: '3.6'

services:
  web:
    restart: always
    build: .
    # command = run on start-up, entrypoint = exclusive...
    entrypoint: ["./docker_launcher.sh"]
    volumes:
      - .:/code
    ports:
      - "5000:5000"

